/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as SubmissionRouteImport } from './routes/submission'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MembersRouteImport } from './routes/members'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ConferenceRouteImport } from './routes/conference'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as NewsNewRouteImport } from './routes/news.new'
import { Route as NewsIdRouteImport } from './routes/news.$id'
import { Route as JournalNewRouteImport } from './routes/journal.new'
import { Route as JournalIdRouteImport } from './routes/journal.$id'
import { Route as GalleryNewRouteImport } from './routes/gallery.new'
import { Route as GalleryIdRouteImport } from './routes/gallery.$id'
import { Route as AdminResourcesRouteImport } from './routes/admin.resources'
import { Route as AdminNoticesRouteImport } from './routes/admin.notices'
import { Route as AdminMembersRouteImport } from './routes/admin.members'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as NewsIdEditRouteImport } from './routes/news.$id.edit'
import { Route as JournalIdEditRouteImport } from './routes/journal.$id.edit'
import { Route as GalleryIdEditRouteImport } from './routes/gallery.$id.edit'

const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionRoute = SubmissionRouteImport.update({
  id: '/submission',
  path: '/submission',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ConferenceRoute = ConferenceRouteImport.update({
  id: '/conference',
  path: '/conference',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const NewsNewRoute = NewsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => NewsRoute,
} as any)
const NewsIdRoute = NewsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NewsRoute,
} as any)
const JournalNewRoute = JournalNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => JournalRoute,
} as any)
const JournalIdRoute = JournalIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => JournalRoute,
} as any)
const GalleryNewRoute = GalleryNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => GalleryRoute,
} as any)
const GalleryIdRoute = GalleryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GalleryRoute,
} as any)
const AdminResourcesRoute = AdminResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNoticesRoute = AdminNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const NewsIdEditRoute = NewsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => NewsIdRoute,
} as any)
const JournalIdEditRoute = JournalIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => JournalIdRoute,
} as any)
const GalleryIdEditRoute = GalleryIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => GalleryIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/conference': typeof ConferenceRoute
  '/gallery': typeof GalleryRouteWithChildren
  '/journal': typeof JournalRouteWithChildren
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/news': typeof NewsRouteWithChildren
  '/register': typeof RegisterRoute
  '/submission': typeof SubmissionRoute
  '/updates': typeof UpdatesRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/gallery/$id': typeof GalleryIdRouteWithChildren
  '/gallery/new': typeof GalleryNewRoute
  '/journal/$id': typeof JournalIdRouteWithChildren
  '/journal/new': typeof JournalNewRoute
  '/news/$id': typeof NewsIdRouteWithChildren
  '/news/new': typeof NewsNewRoute
  '/admin/': typeof AdminIndexRoute
  '/gallery/$id/edit': typeof GalleryIdEditRoute
  '/journal/$id/edit': typeof JournalIdEditRoute
  '/news/$id/edit': typeof NewsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/conference': typeof ConferenceRoute
  '/gallery': typeof GalleryRouteWithChildren
  '/journal': typeof JournalRouteWithChildren
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/news': typeof NewsRouteWithChildren
  '/register': typeof RegisterRoute
  '/submission': typeof SubmissionRoute
  '/updates': typeof UpdatesRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/gallery/$id': typeof GalleryIdRouteWithChildren
  '/gallery/new': typeof GalleryNewRoute
  '/journal/$id': typeof JournalIdRouteWithChildren
  '/journal/new': typeof JournalNewRoute
  '/news/$id': typeof NewsIdRouteWithChildren
  '/news/new': typeof NewsNewRoute
  '/admin': typeof AdminIndexRoute
  '/gallery/$id/edit': typeof GalleryIdEditRoute
  '/journal/$id/edit': typeof JournalIdEditRoute
  '/news/$id/edit': typeof NewsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/conference': typeof ConferenceRoute
  '/gallery': typeof GalleryRouteWithChildren
  '/journal': typeof JournalRouteWithChildren
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/news': typeof NewsRouteWithChildren
  '/register': typeof RegisterRoute
  '/submission': typeof SubmissionRoute
  '/updates': typeof UpdatesRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/gallery/$id': typeof GalleryIdRouteWithChildren
  '/gallery/new': typeof GalleryNewRoute
  '/journal/$id': typeof JournalIdRouteWithChildren
  '/journal/new': typeof JournalNewRoute
  '/news/$id': typeof NewsIdRouteWithChildren
  '/news/new': typeof NewsNewRoute
  '/admin/': typeof AdminIndexRoute
  '/gallery/$id/edit': typeof GalleryIdEditRoute
  '/journal/$id/edit': typeof JournalIdEditRoute
  '/news/$id/edit': typeof NewsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/conference'
    | '/gallery'
    | '/journal'
    | '/login'
    | '/members'
    | '/news'
    | '/register'
    | '/submission'
    | '/updates'
    | '/admin/banners'
    | '/admin/gallery'
    | '/admin/members'
    | '/admin/notices'
    | '/admin/resources'
    | '/gallery/$id'
    | '/gallery/new'
    | '/journal/$id'
    | '/journal/new'
    | '/news/$id'
    | '/news/new'
    | '/admin/'
    | '/gallery/$id/edit'
    | '/journal/$id/edit'
    | '/news/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/conference'
    | '/gallery'
    | '/journal'
    | '/login'
    | '/members'
    | '/news'
    | '/register'
    | '/submission'
    | '/updates'
    | '/admin/banners'
    | '/admin/gallery'
    | '/admin/members'
    | '/admin/notices'
    | '/admin/resources'
    | '/gallery/$id'
    | '/gallery/new'
    | '/journal/$id'
    | '/journal/new'
    | '/news/$id'
    | '/news/new'
    | '/admin'
    | '/gallery/$id/edit'
    | '/journal/$id/edit'
    | '/news/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/conference'
    | '/gallery'
    | '/journal'
    | '/login'
    | '/members'
    | '/news'
    | '/register'
    | '/submission'
    | '/updates'
    | '/admin/banners'
    | '/admin/gallery'
    | '/admin/members'
    | '/admin/notices'
    | '/admin/resources'
    | '/gallery/$id'
    | '/gallery/new'
    | '/journal/$id'
    | '/journal/new'
    | '/news/$id'
    | '/news/new'
    | '/admin/'
    | '/gallery/$id/edit'
    | '/journal/$id/edit'
    | '/news/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ConferenceRoute: typeof ConferenceRoute
  GalleryRoute: typeof GalleryRouteWithChildren
  JournalRoute: typeof JournalRouteWithChildren
  LoginRoute: typeof LoginRoute
  MembersRoute: typeof MembersRoute
  NewsRoute: typeof NewsRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  SubmissionRoute: typeof SubmissionRoute
  UpdatesRoute: typeof UpdatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submission': {
      id: '/submission'
      path: '/submission'
      fullPath: '/submission'
      preLoaderRoute: typeof SubmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conference': {
      id: '/conference'
      path: '/conference'
      fullPath: '/conference'
      preLoaderRoute: typeof ConferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/news/new': {
      id: '/news/new'
      path: '/new'
      fullPath: '/news/new'
      preLoaderRoute: typeof NewsNewRouteImport
      parentRoute: typeof NewsRoute
    }
    '/news/$id': {
      id: '/news/$id'
      path: '/$id'
      fullPath: '/news/$id'
      preLoaderRoute: typeof NewsIdRouteImport
      parentRoute: typeof NewsRoute
    }
    '/journal/new': {
      id: '/journal/new'
      path: '/new'
      fullPath: '/journal/new'
      preLoaderRoute: typeof JournalNewRouteImport
      parentRoute: typeof JournalRoute
    }
    '/journal/$id': {
      id: '/journal/$id'
      path: '/$id'
      fullPath: '/journal/$id'
      preLoaderRoute: typeof JournalIdRouteImport
      parentRoute: typeof JournalRoute
    }
    '/gallery/new': {
      id: '/gallery/new'
      path: '/new'
      fullPath: '/gallery/new'
      preLoaderRoute: typeof GalleryNewRouteImport
      parentRoute: typeof GalleryRoute
    }
    '/gallery/$id': {
      id: '/gallery/$id'
      path: '/$id'
      fullPath: '/gallery/$id'
      preLoaderRoute: typeof GalleryIdRouteImport
      parentRoute: typeof GalleryRoute
    }
    '/admin/resources': {
      id: '/admin/resources'
      path: '/resources'
      fullPath: '/admin/resources'
      preLoaderRoute: typeof AdminResourcesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notices': {
      id: '/admin/notices'
      path: '/notices'
      fullPath: '/admin/notices'
      preLoaderRoute: typeof AdminNoticesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/news/$id/edit': {
      id: '/news/$id/edit'
      path: '/edit'
      fullPath: '/news/$id/edit'
      preLoaderRoute: typeof NewsIdEditRouteImport
      parentRoute: typeof NewsIdRoute
    }
    '/journal/$id/edit': {
      id: '/journal/$id/edit'
      path: '/edit'
      fullPath: '/journal/$id/edit'
      preLoaderRoute: typeof JournalIdEditRouteImport
      parentRoute: typeof JournalIdRoute
    }
    '/gallery/$id/edit': {
      id: '/gallery/$id/edit'
      path: '/edit'
      fullPath: '/gallery/$id/edit'
      preLoaderRoute: typeof GalleryIdEditRouteImport
      parentRoute: typeof GalleryIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBannersRoute: typeof AdminBannersRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminNoticesRoute: typeof AdminNoticesRoute
  AdminResourcesRoute: typeof AdminResourcesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBannersRoute: AdminBannersRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminNoticesRoute: AdminNoticesRoute,
  AdminResourcesRoute: AdminResourcesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface GalleryIdRouteChildren {
  GalleryIdEditRoute: typeof GalleryIdEditRoute
}

const GalleryIdRouteChildren: GalleryIdRouteChildren = {
  GalleryIdEditRoute: GalleryIdEditRoute,
}

const GalleryIdRouteWithChildren = GalleryIdRoute._addFileChildren(
  GalleryIdRouteChildren,
)

interface GalleryRouteChildren {
  GalleryIdRoute: typeof GalleryIdRouteWithChildren
  GalleryNewRoute: typeof GalleryNewRoute
}

const GalleryRouteChildren: GalleryRouteChildren = {
  GalleryIdRoute: GalleryIdRouteWithChildren,
  GalleryNewRoute: GalleryNewRoute,
}

const GalleryRouteWithChildren =
  GalleryRoute._addFileChildren(GalleryRouteChildren)

interface JournalIdRouteChildren {
  JournalIdEditRoute: typeof JournalIdEditRoute
}

const JournalIdRouteChildren: JournalIdRouteChildren = {
  JournalIdEditRoute: JournalIdEditRoute,
}

const JournalIdRouteWithChildren = JournalIdRoute._addFileChildren(
  JournalIdRouteChildren,
)

interface JournalRouteChildren {
  JournalIdRoute: typeof JournalIdRouteWithChildren
  JournalNewRoute: typeof JournalNewRoute
}

const JournalRouteChildren: JournalRouteChildren = {
  JournalIdRoute: JournalIdRouteWithChildren,
  JournalNewRoute: JournalNewRoute,
}

const JournalRouteWithChildren =
  JournalRoute._addFileChildren(JournalRouteChildren)

interface NewsIdRouteChildren {
  NewsIdEditRoute: typeof NewsIdEditRoute
}

const NewsIdRouteChildren: NewsIdRouteChildren = {
  NewsIdEditRoute: NewsIdEditRoute,
}

const NewsIdRouteWithChildren =
  NewsIdRoute._addFileChildren(NewsIdRouteChildren)

interface NewsRouteChildren {
  NewsIdRoute: typeof NewsIdRouteWithChildren
  NewsNewRoute: typeof NewsNewRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsIdRoute: NewsIdRouteWithChildren,
  NewsNewRoute: NewsNewRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ConferenceRoute: ConferenceRoute,
  GalleryRoute: GalleryRouteWithChildren,
  JournalRoute: JournalRouteWithChildren,
  LoginRoute: LoginRoute,
  MembersRoute: MembersRoute,
  NewsRoute: NewsRouteWithChildren,
  RegisterRoute: RegisterRoute,
  SubmissionRoute: SubmissionRoute,
  UpdatesRoute: UpdatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
